### ISSUE TITLE
Fix board not found issue

### ISSUE THREAD

**Issue by mattsm** [lgirdk/boardfarm#116]
This should print a much better error message:

```
$ ./bft -n board_not_in_inventory -e lan2_ping_lan
Traceback (most recent call last):
  File "./bft", line 432, in <module>
    main()
  File "./bft", line 88, in main
    config.BOARD_NAMES = sorted(config.BOARD_NAMES, key=lambda x: 'feature' in config.boardfarm_config[x])
  File "./bft", line 88, in <lambda>
    config.BOARD_NAMES = sorted(config.BOARD_NAMES, key=lambda x: 'feature' in config.boardfarm_config[x])
KeyError: 'mv1-4'
```

**Comment by mbanders** [comment]
Fixed by https://github.com/lgirdk/boardfarm/commit/ef13213ca830a6f7aee3149cbad47eeec5c49534
