### ISSUE TITLE
Error: Device on LAN couldn't obtain address via DHCP

### ISSUE THREAD

**Issue by sravichandran-contractor** [lgirdk/boardfarm#326]
Script log -- http://172.16.1.237:7777/suviqetoxu - NTL7465LG__P3__621

root@bft-node-enp1s0-108-0:~# dhclient -4 -v eth1
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth1/a6:4e:ce:1c:ad:53
Sending on   LPF/eth1/a6:4e:ce:1c:ad:53
Sending on   Socket/fallback
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 6
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 7
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 8
DHCPDISCOVER on eth1 to 255.255.255.255 port 67 interval 9

=========== Test failed! Running recovery Time: Thu 20 Jun 2019 20:58:59	 ===========
Error: Device on LAN couldn't obtain address via DHCP.
Traceback (most recent call last):
  File "/home/shakthi/Documents/boardfarm/tests/linux_boot.py", line 92, in testWrapper
    self.runTest()
  File "/home/shakthi/Documents/boardfarm/devices/../tests/lib/logging.py", line 48, in wrapper
    ret = func(*args, **kwargs)
  File "/home/shakthi/Documents/boardfarm-cbn/tests/InternetServices.py", line 447, in runTest
    super(NTL7465LG__P3__621, self).runTest()
  File "/home/shakthi/Documents/boardfarm/devices/../tests/lib/logging.py", line 48, in wrapper
    ret = func(*args, **kwargs)
  File "/home/shakthi/Documents/boardfarm-cbn/tests/InternetServices.py", line 98, in runTest
    lan.start_lan_client(wan_gw=wan.gw)
  File "/home/shakthi/Documents/boardfarm/devices/../tests/lib/logging.py", line 48, in wrapper
    ret = func(*args, **kwargs)
  File "/home/shakthi/Documents/boardfarm/devices/debian.py", line 644, in start_lan_client
    raise Exception("Error: Device on LAN couldn't obtain address via DHCP.")
Exception: Error: Device on LAN couldn't obtain address via DHCP.

		==

**Comment by Parumugam** [comment]
Fix added by @ketantewari . 
https://review.gerrithub.io/c/lgirdk/boardfarm/+/458869
@sravichandran-contractor  to retest.
